/**
 * Curated static jobs — manually sourced buy-side roles.
 * Dates are YYYY-MM-DD. daysAgo is computed at call time so results
 * respect the caller's maxDays filter.
 */

import { JobSignal, JobCategory, JobSignalTag } from "@/app/types";

interface StaticJob {
  firm: string;
  role: string;
  category: JobCategory;
  location: string;
  dateAdded: string; // YYYY-MM-DD
  url?: string;
  signalTag: JobSignalTag;
  why: string;
}

const STATIC_JOBS: StaticJob[] = [
  // ── Public Credit — US Asset Managers ────────────────────────────────────
  {
    firm: "PIMCO",
    role: "Credit Research Analyst",
    category: "Public Credit",
    location: "Newport Beach",
    dateAdded: "2026-02-14",
    url: "https://www.pimco.com/en-us/careers",
    signalTag: "Fund scaling",
    why: "PIMCO expanding credit research coverage across corporate and structured credit.",
  },
  {
    firm: "PIMCO",
    role: "Portfolio Manager – High Yield",
    category: "Public Credit",
    location: "New York",
    dateAdded: "2026-01-22",
    url: "https://www.pimco.com/en-us/careers",
    signalTag: "Fund scaling",
    why: "Senior hire into PIMCO's flagship high yield platform.",
  },
  {
    firm: "Wellington Management",
    role: "Fixed Income Research Analyst",
    category: "Public Credit",
    location: "Boston",
    dateAdded: "2026-02-05",
    url: "https://www.wellington.com/en/careers",
    signalTag: "Post-raise build-out",
    why: "Wellington building out IG credit coverage team.",
  },
  {
    firm: "Wellington Management",
    role: "Credit Analyst – Leveraged Finance",
    category: "Public Credit",
    location: "Boston",
    dateAdded: "2026-01-15",
    url: "https://www.wellington.com/en/careers",
    signalTag: "Fund scaling",
    why: "Leveraged loans and HY coverage expansion at Wellington.",
  },
  {
    firm: "BlackRock",
    role: "Credit Research Analyst – Investment Grade",
    category: "Public Credit",
    location: "New York",
    dateAdded: "2026-02-20",
    url: "https://careers.blackrock.com",
    signalTag: "Fund scaling",
    why: "BlackRock IG credit team adding analyst amid ETF AUM growth.",
  },
  {
    firm: "BlackRock",
    role: "Associate – Private Credit Origination",
    category: "Private Credit",
    location: "New York",
    dateAdded: "2026-02-01",
    url: "https://careers.blackrock.com",
    signalTag: "Post-raise build-out",
    why: "BlackRock direct lending platform scaling after $10B+ fundraise.",
  },
  {
    firm: "TCW Group",
    role: "High Yield Credit Analyst",
    category: "Public Credit",
    location: "Los Angeles",
    dateAdded: "2026-01-28",
    url: "https://www.tcw.com/careers",
    signalTag: "Fund scaling",
    why: "TCW expanding HY team after strong AUM growth.",
  },
  {
    firm: "TCW Group",
    role: "CLO Portfolio Manager",
    category: "Private Credit",
    location: "Los Angeles",
    dateAdded: "2025-12-10",
    url: "https://www.tcw.com/careers",
    signalTag: "New fund",
    why: "TCW CLO franchise hiring PM ahead of new CLO issuance.",
  },
  {
    firm: "Lord Abbett",
    role: "Credit Research Analyst",
    category: "Public Credit",
    location: "Jersey City",
    dateAdded: "2026-02-18",
    url: "https://www.lordabbett.com/careers",
    signalTag: "Fund scaling",
    why: "Lord Abbett adding credit coverage with AUM approaching $200B.",
  },
  {
    firm: "MFS Investment Management",
    role: "Fixed Income Portfolio Manager",
    category: "Public Credit",
    location: "Boston",
    dateAdded: "2026-01-10",
    url: "https://www.mfs.com/en-us/about-mfs/careers",
    signalTag: "Fund scaling",
    why: "MFS building out multi-sector fixed income capabilities.",
  },
  {
    firm: "Allspring Global Investments",
    role: "Credit Analyst – High Yield",
    category: "Public Credit",
    location: "Charlotte",
    dateAdded: "2026-02-03",
    url: "https://www.allspringglobal.com/careers",
    signalTag: "Post-raise build-out",
    why: "Allspring repositioning fixed income platform post-Wells Fargo spin-off.",
  },
  {
    firm: "Franklin Templeton",
    role: "Senior Credit Analyst – Leveraged Loans",
    category: "Public Credit",
    location: "San Mateo",
    dateAdded: "2026-01-20",
    url: "https://www.franklintempleton.com/about-us/careers",
    signalTag: "Fund scaling",
    why: "Franklin Templeton loan platform scaling; Benefit Street integration ongoing.",
  },
  {
    firm: "T. Rowe Price",
    role: "Credit Analyst – High Yield & Leveraged Finance",
    category: "Public Credit",
    location: "Baltimore",
    dateAdded: "2026-02-12",
    url: "https://careers.troweprice.com",
    signalTag: "Fund scaling",
    why: "T. Rowe expanding HY coverage team as credit allocation increases.",
  },
  {
    firm: "Nuveen",
    role: "Private Credit Associate",
    category: "Private Credit",
    location: "Chicago",
    dateAdded: "2026-01-30",
    url: "https://www.nuveen.com/en-us/careers",
    signalTag: "Post-raise build-out",
    why: "Nuveen private credit platform growing; TIAA parent backing.",
  },
  {
    firm: "Western Asset Management",
    role: "Credit Research Analyst – EM",
    category: "Public Credit",
    location: "Pasadena",
    dateAdded: "2025-12-18",
    url: "https://www.westernasset.com/about/careers",
    signalTag: "Fund scaling",
    why: "Western Asset expanding EM credit coverage capability.",
  },
  // ── Rating Agencies ───────────────────────────────────────────────────────
  {
    firm: "Moody's Ratings",
    role: "Credit Analyst – Leveraged Finance",
    category: "Public Credit",
    location: "New York",
    dateAdded: "2026-02-22",
    url: "https://careers.moodys.com",
    signalTag: "Fund scaling",
    why: "Moody's lev fin team adding analysts amid surge in LBO activity.",
  },
  {
    firm: "Moody's Ratings",
    role: "VP – CLO Ratings",
    category: "Public Credit",
    location: "New York",
    dateAdded: "2026-01-25",
    url: "https://careers.moodys.com",
    signalTag: "Fund scaling",
    why: "CLO market rebound driving hiring at Moody's structured credit desk.",
  },
  {
    firm: "Fitch Ratings",
    role: "Associate Director – Corporate Credit",
    category: "Public Credit",
    location: "New York",
    dateAdded: "2026-02-08",
    url: "https://www.fitchgroup.com/careers",
    signalTag: "Fund scaling",
    why: "Fitch broadening corporate credit coverage across sectors.",
  },
  {
    firm: "Fitch Ratings",
    role: "Analyst – Leveraged Finance",
    category: "Public Credit",
    location: "Chicago",
    dateAdded: "2026-01-14",
    url: "https://www.fitchgroup.com/careers",
    signalTag: "Fund scaling",
    why: "Fitch lev fin desk hiring as sponsored deal flow picks up.",
  },
  {
    firm: "S&P Global Ratings",
    role: "Credit Analyst – Private Credit Assessments",
    category: "Public Credit",
    location: "New York",
    dateAdded: "2026-02-17",
    url: "https://careers.spglobal.com",
    signalTag: "New fund",
    why: "S&P Private Credit Assessments team scaling to meet market demand.",
  },
  {
    firm: "KBRA",
    role: "Senior Analyst – ABS / CLO",
    category: "Public Credit",
    location: "New York",
    dateAdded: "2026-01-07",
    url: "https://www.kbra.com/careers",
    signalTag: "Post-raise build-out",
    why: "KBRA growing structured credit team as CLO issuance rebounds.",
  },
  // ── Private Credit / Direct Lending — US ─────────────────────────────────
  {
    firm: "Apollo Global Management",
    role: "Vice President – Direct Lending",
    category: "Private Credit",
    location: "New York",
    dateAdded: "2026-02-25",
    url: "https://www.apollo.com/careers",
    signalTag: "Post-raise build-out",
    why: "Apollo's $25B direct lending fund finalising — VP hire ahead of deployment.",
  },
  {
    firm: "Apollo Global Management",
    role: "Associate – Credit Origination",
    category: "Private Credit",
    location: "New York",
    dateAdded: "2026-01-17",
    url: "https://www.apollo.com/careers",
    signalTag: "In-market raise",
    why: "Apollo actively raising Hybrid Value and direct lending vehicles.",
  },
  {
    firm: "Ares Management",
    role: "Associate – Direct Lending",
    category: "Private Credit",
    location: "Los Angeles",
    dateAdded: "2026-02-10",
    url: "https://www.aresmgmt.com/careers",
    signalTag: "In-market raise",
    why: "Ares ARCC and Europa X funds in market; growing origination team.",
  },
  {
    firm: "Ares Management",
    role: "Vice President – Credit Portfolio Management",
    category: "Private Credit",
    location: "New York",
    dateAdded: "2026-01-28",
    url: "https://www.aresmgmt.com/careers",
    signalTag: "Fund scaling",
    why: "Ares credit AUM exceeds $350B; portfolio monitoring team expanding.",
  },
  {
    firm: "KKR",
    role: "Associate – Private Credit",
    category: "Private Credit",
    location: "New York",
    dateAdded: "2026-02-19",
    url: "https://www.kkr.com/careers",
    signalTag: "Post-raise build-out",
    why: "KKR direct lending build-out continues following $10B credit fundraise.",
  },
  {
    firm: "Blue Owl Capital",
    role: "Associate – Direct Lending",
    category: "Private Credit",
    location: "New York",
    dateAdded: "2026-02-04",
    url: "https://www.blueowlcapital.com/careers",
    signalTag: "In-market raise",
    why: "Blue Owl BDC and Owl Rock funds in active fundraising; team scaling.",
  },
  {
    firm: "Blue Owl Capital",
    role: "Director – Origination",
    category: "Private Credit",
    location: "Chicago",
    dateAdded: "2026-01-09",
    url: "https://www.blueowlcapital.com/careers",
    signalTag: "Fund scaling",
    why: "Blue Owl expanding origination coverage to Midwest sponsored deals.",
  },
  {
    firm: "HPS Investment Partners",
    role: "Vice President – Special Situations",
    category: "Private Credit",
    location: "New York",
    dateAdded: "2026-02-13",
    url: "https://www.hpsinvest.com/careers",
    signalTag: "Post-raise build-out",
    why: "HPS integration into BlackRock accelerating; special sits team building.",
  },
  {
    firm: "Golub Capital",
    role: "Associate – One-Stop Lending",
    category: "Private Credit",
    location: "New York",
    dateAdded: "2026-01-24",
    url: "https://www.golubcapital.com/careers",
    signalTag: "Fund scaling",
    why: "Golub BDC and private credit AUM approaching $75B; team scaling.",
  },
  {
    firm: "Antares Capital",
    role: "Senior Associate – Credit",
    category: "Private Credit",
    location: "Chicago",
    dateAdded: "2026-02-06",
    url: "https://www.antarescapital.com/careers",
    signalTag: "Fund scaling",
    why: "Antares remains most active middle market lender; regular associate intake.",
  },
  {
    firm: "Benefit Street Partners",
    role: "Associate – Direct Lending",
    category: "Private Credit",
    location: "New York",
    dateAdded: "2026-01-21",
    url: "https://www.benefitstreetpartners.com",
    signalTag: "Post-raise build-out",
    why: "BSP middle market fund V in market; team expanding to manage deployment.",
  },
  {
    firm: "Carlyle Credit",
    role: "Associate – Structured Credit",
    category: "Private Credit",
    location: "New York",
    dateAdded: "2026-02-16",
    url: "https://www.carlyle.com/careers",
    signalTag: "New fund",
    why: "Carlyle launching new CLO and structured credit vehicles.",
  },
  {
    firm: "Neuberger Berman",
    role: "Associate – Private Credit",
    category: "Private Credit",
    location: "New York",
    dateAdded: "2026-01-13",
    url: "https://www.nb.com/careers",
    signalTag: "Fund scaling",
    why: "NB credit AUM growing rapidly; direct lending and CLO platforms expanding.",
  },
  {
    firm: "TPG Angelo Gordon",
    role: "Vice President – Direct Lending",
    category: "Private Credit",
    location: "New York",
    dateAdded: "2026-02-07",
    url: "https://www.tpg.com/careers",
    signalTag: "Post-raise build-out",
    why: "TPG AG mid-market fund IV above target; team expanding ahead of close.",
  },
  {
    firm: "Sixth Street Partners",
    role: "Associate – Credit",
    category: "Private Credit",
    location: "New York",
    dateAdded: "2026-01-19",
    url: "https://www.sixthstreet.com/careers",
    signalTag: "Fund scaling",
    why: "Sixth Street Specialty Lending and TAO fund scaling; analyst/associate intake.",
  },
  {
    firm: "Crescent Capital Group",
    role: "Associate – Direct Lending",
    category: "Private Credit",
    location: "Los Angeles",
    dateAdded: "2026-02-11",
    url: "https://www.crescentcapitalgroup.com",
    signalTag: "In-market raise",
    why: "Crescent 5th direct lending fund in market; origination team growing.",
  },
  {
    firm: "Monroe Capital",
    role: "Associate – Lower Middle Market Lending",
    category: "Private Credit",
    location: "Chicago",
    dateAdded: "2026-01-08",
    url: "https://www.monroecapitalllc.com",
    signalTag: "Fund scaling",
    why: "Monroe Capital expanding presence in lower middle market lending.",
  },
  {
    firm: "Churchill Asset Management",
    role: "Associate – Unitranche / One-Stop",
    category: "Private Credit",
    location: "New York",
    dateAdded: "2026-02-02",
    url: "https://www.churchillam.com",
    signalTag: "Post-raise build-out",
    why: "Churchill (Nuveen affiliate) growing unitranche book; team scaling.",
  },
  {
    firm: "Barings",
    role: "Credit Analyst – Private Finance",
    category: "Private Credit",
    location: "Charlotte",
    dateAdded: "2026-01-16",
    url: "https://www.barings.com/careers",
    signalTag: "Fund scaling",
    why: "Barings private finance AUM exceeds $40B; analyst hire in US platform.",
  },
  // ── Distressed / Special Situations ──────────────────────────────────────
  {
    firm: "Oaktree Capital Management",
    role: "Associate – Distressed Opportunities",
    category: "Private Credit",
    location: "Los Angeles",
    dateAdded: "2026-02-23",
    url: "https://www.oaktreecapital.com/careers",
    signalTag: "In-market raise",
    why: "Oaktree Opps XI in market at $18B target; distressed team expanding.",
  },
  {
    firm: "Oaktree Capital Management",
    role: "Vice President – High Yield Bonds",
    category: "Public Credit",
    location: "Los Angeles",
    dateAdded: "2026-01-26",
    url: "https://www.oaktreecapital.com/careers",
    signalTag: "Fund scaling",
    why: "Oaktree HY platform adding VP as spreads tighten and positioning shifts.",
  },
  {
    firm: "Centerbridge Partners",
    role: "Associate – Special Situations",
    category: "Private Credit",
    location: "New York",
    dateAdded: "2026-02-15",
    url: "https://www.centerbridgepartners.com/careers",
    signalTag: "In-market raise",
    why: "Centerbridge credit fund VI approaching $7B close; team hiring.",
  },
  {
    firm: "Bain Capital Credit",
    role: "Associate – Opportunistic Credit",
    category: "Private Credit",
    location: "Boston",
    dateAdded: "2026-01-31",
    url: "https://www.baincapital.com/careers",
    signalTag: "Fund scaling",
    why: "Bain Credit European and US special situations expanding.",
  },
  {
    firm: "Elliott Management",
    role: "Credit Analyst – Special Situations",
    category: "Private Credit",
    location: "New York",
    dateAdded: "2026-02-09",
    url: "https://www.elliottmgmt.com",
    signalTag: "Fund scaling",
    why: "Elliott adding credit analysts to support growing AUM base ($70B+).",
  },
  {
    firm: "Cerberus Capital Management",
    role: "Associate – Distressed Credit",
    category: "Private Credit",
    location: "New York",
    dateAdded: "2026-01-04",
    url: "https://www.cerberuscapital.com",
    signalTag: "Fund scaling",
    why: "Cerberus distressed strategy expanding; credit hire in US platform.",
  },
  {
    firm: "Fortress Investment Group",
    role: "Credit Analyst",
    category: "Private Credit",
    location: "New York",
    dateAdded: "2026-02-27",
    url: "https://www.fortress.com/careers",
    signalTag: "Post-raise build-out",
    why: "Fortress credit fund VIII raised $6B+; team building out.",
  },
  {
    firm: "King Street Capital",
    role: "Associate – Distressed Debt",
    category: "Private Credit",
    location: "New York",
    dateAdded: "2026-01-22",
    url: "https://www.kingstreetcapital.com",
    signalTag: "Fund scaling",
    why: "King Street event-driven credit strategy adding capacity.",
  },
  {
    firm: "Marathon Asset Management",
    role: "Credit Analyst – European Special Situations",
    category: "Private Credit",
    location: "New York",
    dateAdded: "2026-02-03",
    url: "https://www.marathonam.com",
    signalTag: "New fund",
    why: "Marathon launching European credit vehicle; NYC-based analyst needed.",
  },
  {
    firm: "Monarch Alternative Capital",
    role: "Associate – Event-Driven Credit",
    category: "Private Credit",
    location: "New York",
    dateAdded: "2026-01-18",
    url: "https://www.monarchalternative.com",
    signalTag: "Fund scaling",
    why: "Monarch credit platform growing; special situations focus.",
  },
  {
    firm: "Brigade Capital Management",
    role: "Credit Analyst – High Yield",
    category: "Public Credit",
    location: "New York",
    dateAdded: "2026-02-21",
    url: "https://www.brigadecapital.com",
    signalTag: "Fund scaling",
    why: "Brigade HY and credit opportunity fund hiring as AUM grows.",
  },
  {
    firm: "Silver Point Capital",
    role: "Associate – Distressed & Special Situations",
    category: "Private Credit",
    location: "Greenwich",
    dateAdded: "2026-01-29",
    url: "https://www.silverpointcapital.com",
    signalTag: "Fund scaling",
    why: "Silver Point credit and distressed franchise growing AUM.",
  },
  {
    firm: "Canyon Capital Advisors",
    role: "Credit Analyst",
    category: "Private Credit",
    location: "Los Angeles",
    dateAdded: "2026-01-06",
    url: "https://www.canyonpartners.com",
    signalTag: "Fund scaling",
    why: "Canyon multi-strategy credit platform expanding analyst team.",
  },
  {
    firm: "Whitebox Advisors",
    role: "Analyst – Multi-Strategy Credit",
    category: "Private Credit",
    location: "Minneapolis",
    dateAdded: "2026-02-26",
    url: "https://www.whiteboxadvisors.com",
    signalTag: "Fund scaling",
    why: "Whitebox credit and arbitrage strategies expanding.",
  },
  // ── CLO / Structured Credit ───────────────────────────────────────────────
  {
    firm: "Octagon Credit Investors",
    role: "CLO Associate / Portfolio Analyst",
    category: "Private Credit",
    location: "New York",
    dateAdded: "2026-02-24",
    url: "https://www.octagoninv.com",
    signalTag: "New fund",
    why: "Octagon pricing two new CLOs in Q1 2026; analyst hire to support.",
  },
  {
    firm: "CIFC Asset Management",
    role: "Leveraged Loan Analyst",
    category: "Private Credit",
    location: "New York",
    dateAdded: "2026-01-12",
    url: "https://www.cifcam.com",
    signalTag: "New fund",
    why: "CIFC CLO issuance active in 2026; loan analyst needed for new deals.",
  },
  {
    firm: "Sound Point Capital",
    role: "CLO Portfolio Manager",
    category: "Private Credit",
    location: "New York",
    dateAdded: "2026-02-17",
    url: "https://www.soundpointcapital.com",
    signalTag: "Fund scaling",
    why: "Sound Point managing $35B+ in CLOs; PM hire for new vehicle.",
  },
  {
    firm: "Palmer Square Capital Management",
    role: "Analyst – CLO / Structured Credit",
    category: "Private Credit",
    location: "Kansas City",
    dateAdded: "2026-01-23",
    url: "https://palmersquarecapital.com",
    signalTag: "New fund",
    why: "Palmer Square new CLO in 2026 pipeline; analyst support needed.",
  },
  // ── Multi-Strategy / Hedge Funds ─────────────────────────────────────────
  {
    firm: "Citadel",
    role: "Credit Analyst – HY / Leveraged Finance",
    category: "Public Credit",
    location: "New York",
    dateAdded: "2026-02-28",
    url: "https://www.citadel.com/careers",
    signalTag: "Fund scaling",
    why: "Citadel credit pod adding analyst capacity; competitive process.",
  },
  {
    firm: "Citadel",
    role: "Structured Products Analyst",
    category: "Private Credit",
    location: "Chicago",
    dateAdded: "2026-01-27",
    url: "https://www.citadel.com/careers",
    signalTag: "Fund scaling",
    why: "Citadel structured products desk expansion in Chicago.",
  },
  {
    firm: "Point72",
    role: "Credit Analyst – Distressed",
    category: "Private Credit",
    location: "Stamford",
    dateAdded: "2026-02-18",
    url: "https://www.point72.com/careers",
    signalTag: "Fund scaling",
    why: "Point72 credit pod hiring; distressed focus with multi-strat support.",
  },
  {
    firm: "Millennium Management",
    role: "Credit PM / Analyst – Special Situations",
    category: "Private Credit",
    location: "New York",
    dateAdded: "2026-01-05",
    url: "https://www.mlp.com/careers",
    signalTag: "Fund scaling",
    why: "Millennium pod expansion; credit special sits hiring across desks.",
  },
  {
    firm: "Sculptor Capital Management",
    role: "Credit Analyst – Opportunistic",
    category: "Private Credit",
    location: "New York",
    dateAdded: "2026-02-14",
    url: "https://www.sculptor.com/careers",
    signalTag: "Fund scaling",
    why: "Sculptor (Rithm affiliate) credit platform growing post-merger.",
  },
  {
    firm: "Baupost Group",
    role: "Investment Analyst – Credit",
    category: "Private Credit",
    location: "Boston",
    dateAdded: "2026-01-03",
    url: "https://www.baupost.com",
    signalTag: "Fund scaling",
    why: "Baupost rare hire; value-oriented credit and distressed focus.",
  },
  // ── BDC ───────────────────────────────────────────────────────────────────
  {
    firm: "Prospect Capital",
    role: "Associate – Middle Market Direct Lending",
    category: "Private Credit",
    location: "New York",
    dateAdded: "2026-02-20",
    url: "https://www.prospectstreet.com",
    signalTag: "Fund scaling",
    why: "Prospect Capital BDC adding deal team associates.",
  },
  {
    firm: "Main Street Capital",
    role: "Investment Analyst",
    category: "Private Credit",
    location: "Houston",
    dateAdded: "2026-01-16",
    url: "https://www.mainstcapital.com",
    signalTag: "Fund scaling",
    why: "Main Street Capital BDC adding analyst to growing deal team.",
  },
  {
    firm: "Hercules Capital",
    role: "Associate – Venture Lending",
    category: "Private Credit",
    location: "Palo Alto",
    dateAdded: "2026-02-06",
    url: "https://www.htgc.com/careers",
    signalTag: "New fund",
    why: "Hercules venture debt BDC expanding team as tech lending rebounds.",
  },
  {
    firm: "New Mountain Finance",
    role: "Credit Associate",
    category: "Private Credit",
    location: "New York",
    dateAdded: "2026-01-28",
    url: "https://www.newmountainfinance.com",
    signalTag: "Fund scaling",
    why: "NMFC BDC growing upper middle market lending platform.",
  },
  // ── Canada ────────────────────────────────────────────────────────────────
  {
    firm: "Ontario Teachers' Pension Plan",
    role: "Credit Analyst – Fixed Income",
    category: "Public Credit",
    location: "Toronto",
    dateAdded: "2026-02-11",
    url: "https://careers.otpp.com",
    signalTag: "Fund scaling",
    why: "OTPP fixed income team expanding as credit allocation grows.",
  },
  {
    firm: "CPP Investments",
    role: "Associate – Private Credit",
    category: "Private Credit",
    location: "Toronto",
    dateAdded: "2026-01-14",
    url: "https://www.cppinvestments.com/careers",
    signalTag: "Fund scaling",
    why: "CPP credit investing team growing; direct lending focus.",
  },
  {
    firm: "Brookfield Asset Management",
    role: "Associate – Credit Strategies",
    category: "Private Credit",
    location: "Toronto",
    dateAdded: "2026-02-08",
    url: "https://www.brookfield.com/careers",
    signalTag: "Post-raise build-out",
    why: "Brookfield credit fundraise above $10B; team hire in Toronto HQ.",
  },
  {
    firm: "Caisse de dépôt et placement (CDPQ)",
    role: "Credit Analyst",
    category: "Public Credit",
    location: "Montréal",
    dateAdded: "2026-01-21",
    url: "https://www.cdpq.com/en/careers",
    signalTag: "Fund scaling",
    why: "CDPQ fixed income and credit team growing with Canadian AUM expansion.",
  },
  {
    firm: "OMERS",
    role: "Associate – Private Credit",
    category: "Private Credit",
    location: "Toronto",
    dateAdded: "2026-02-24",
    url: "https://www.omers.com/careers",
    signalTag: "Fund scaling",
    why: "OMERS Ventures and private credit scaling as plan assets grow.",
  },
  // ── UK / Europe ───────────────────────────────────────────────────────────
  {
    firm: "ICG (Intermediate Capital Group)",
    role: "Associate – Senior Debt",
    category: "Private Credit",
    location: "London",
    dateAdded: "2026-02-19",
    url: "https://www.icgam.com/careers",
    signalTag: "In-market raise",
    why: "ICG European senior debt fund VII above €6B; origination hiring.",
  },
  {
    firm: "ICG (Intermediate Capital Group)",
    role: "Analyst – CLO Management",
    category: "Private Credit",
    location: "London",
    dateAdded: "2026-01-11",
    url: "https://www.icgam.com/careers",
    signalTag: "New fund",
    why: "ICG CLO team launching new vehicle; analyst support hire.",
  },
  {
    firm: "Barings",
    role: "Associate – European Private Finance",
    category: "Private Credit",
    location: "London",
    dateAdded: "2026-02-15",
    url: "https://www.barings.com/careers",
    signalTag: "Fund scaling",
    why: "Barings European private finance growing amid strong sponsor deal flow.",
  },
  {
    firm: "Permira Credit",
    role: "Investment Analyst",
    category: "Private Credit",
    location: "London",
    dateAdded: "2026-01-07",
    url: "https://www.permira.com/careers",
    signalTag: "Post-raise build-out",
    why: "Permira Credit fund V at €5B; analyst hire ahead of deployment.",
  },
  {
    firm: "Pemberton Asset Management",
    role: "Senior Associate – Direct Lending",
    category: "Private Credit",
    location: "London",
    dateAdded: "2026-02-22",
    url: "https://www.pembertonasset.com",
    signalTag: "Fund scaling",
    why: "Pemberton European mid-market lending platform exceeds €10B.",
  },
  // ── Investment Banking / Sell-Side ────────────────────────────────────────
  {
    firm: "Goldman Sachs",
    role: "Associate – Leveraged Finance",
    category: "Investment Banking",
    location: "New York",
    dateAdded: "2026-02-26",
    url: "https://www.goldmansachs.com/careers",
    signalTag: "Fund scaling",
    why: "Goldman LevFin rebuilding headcount ahead of LBO pipeline recovery.",
  },
  {
    firm: "Morgan Stanley",
    role: "Analyst – Debt Capital Markets",
    category: "Investment Banking",
    location: "New York",
    dateAdded: "2026-01-30",
    url: "https://www.morganstanley.com/careers",
    signalTag: "Fund scaling",
    why: "MS DCM coverage adding analyst; IG and HY deal pipeline building.",
  },
  {
    firm: "Jefferies",
    role: "Associate – High Yield Capital Markets",
    category: "Investment Banking",
    location: "New York",
    dateAdded: "2026-02-16",
    url: "https://www.jefferies.com/careers",
    signalTag: "Post-raise build-out",
    why: "Jefferies leveraged finance franchise growing share in mid-market.",
  },
  {
    firm: "Houlihan Lokey",
    role: "Analyst – Financial Restructuring",
    category: "Investment Banking",
    location: "New York",
    dateAdded: "2026-01-25",
    url: "https://www.hl.com/careers",
    signalTag: "Fund scaling",
    why: "HL restructuring group adding analyst as distressed pipeline grows.",
  },
  {
    firm: "Lazard",
    role: "Associate – Restructuring Advisory",
    category: "Investment Banking",
    location: "New York",
    dateAdded: "2026-02-09",
    url: "https://www.lazard.com/careers",
    signalTag: "Fund scaling",
    why: "Lazard FAS group hiring as distressed situations increase globally.",
  },
  {
    firm: "PJT Partners",
    role: "Analyst – Restructuring",
    category: "Investment Banking",
    location: "New York",
    dateAdded: "2026-02-03",
    url: "https://www.pjtpartners.com/careers",
    signalTag: "Post-raise build-out",
    why: "PJT Park Hill and restructuring growing; analyst intake active.",
  },
  // ── IR / Investor Relations ───────────────────────────────────────────────
  {
    firm: "Ares Management",
    role: "Vice President – Investor Relations, Credit",
    category: "IR / Ops",
    location: "New York",
    dateAdded: "2026-02-01",
    url: "https://www.aresmgmt.com/careers",
    signalTag: "Fund scaling",
    why: "Ares credit IR team scaling as institutional LP base grows.",
  },
  {
    firm: "Apollo Global Management",
    role: "Associate – Investor Relations",
    category: "IR / Ops",
    location: "New York",
    dateAdded: "2026-01-26",
    url: "https://www.apollo.com/careers",
    signalTag: "Fund scaling",
    why: "Apollo global credit IR expanding with new fund raises.",
  },
  {
    firm: "Oaktree Capital Management",
    role: "Associate – Investor Relations",
    category: "IR / Ops",
    location: "Los Angeles",
    dateAdded: "2026-02-12",
    url: "https://www.oaktreecapital.com/careers",
    signalTag: "In-market raise",
    why: "Oaktree Opps XI fundraise driving IR team expansion.",
  },
];

/**
 * Returns static curated jobs filtered to maxDays recency.
 * daysAgo is computed fresh on each call so it stays accurate.
 */
export function getStaticJobs(maxDays: number): JobSignal[] {
  const today = new Date();
  const out: JobSignal[] = [];
  STATIC_JOBS.forEach((j, i) => {
    const added = new Date(j.dateAdded);
    const days = Math.floor((today.getTime() - added.getTime()) / 86_400_000);
    if (days > maxDays) return;
    out.push({
      id: `curated-${i}`,
      firm: j.firm,
      role: j.role,
      category: j.category,
      location: j.location,
      daysAgo: days,
      signalTag: j.signalTag,
      why: j.why,
      score: 0,
      edgarUrl: j.url,
      source: "curated",
    });
  });
  return out;
}
